# -*- coding: utf-8 -*-
"""ESCAPE CHARACTERS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AeeTivAuRIdSRjEa6aEmwEvUDwaRoHgg
"""

print ('dia berkata: "pergilah ke rumah"')

print ("aku menimpali: \"apakah kau ingin aku 'angkat tangan'?!\"")