# -*- coding: utf-8 -*-
"""manipulasi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wi7bB_ySBkeKcdOs1hbJ9htMxiyyu22A

**STRING**
"""

nama = 'elgira'
asal = 'rajabsa'
#print (nama,asal)
#print("halo nama saya",nama)
#print ("halo nama saya",nama ,"äsal saya dari",asal)

data_lengkap = nama + asal
#print (data_lengkap)
#print (nama)

"""STRING NON **STRING**"""

asal_kota = "bandar lampung"
kode_pos = 23341

asal_kota_kode_pos = asal_kota + str(kode_pos)
print (asal_kota_kode_pos)

asal_kota_x3 = asal_kota * 3
print (asal_kota_x3)