# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jE_mkVVOEWkIHyu5VDOF8uPBtW_3dzxX

ELGIRA DYVA SAPUTRA
2411012001
"""

nama =  'gilbert'
usia = 20
lajang = True

print(type(nama))
print(type(usia))
print(type(lajang))

usia = input ('masukan usia anda: ')
print(type(usia))

a = 10 / 2
print(type(a))

b = 1 / 2
print(type(b))

panjang= int(input('masukan panjang: '))
lebar = float(input('masukan lebar: '))

luas = panjang * lebar
print('luas =', panjang * lebar)

kata = 'jeruk' * 5
print(kata)
print(type(kata))

nama = 'boy'
tahun_lahir = 2006

print(nama + ' lahir di tahun ' + str(tahun_lahir))